# Generated by Django 4.2.6 on 2023-10-17 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_purchaseorder_purchaseorderitem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='products',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='purchaseorderitem',
            old_name='product',
            new_name='item',
        ),
    ]
