# Generated by Django 4.2.6 on 2023-11-01 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_rename_products_purchaseorder_items_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorderitem',
            old_name='item',
            new_name='product',
        ),
    ]
