# Generated by Django 4.2.6 on 2023-11-01 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_rename_item_purchaseorderitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorderitem',
            old_name='product',
            new_name='item',
        ),
    ]
