# Generated by Django 4.2.6 on 2023-11-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0007_remove_purchaseorder_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='items',
            field=models.ManyToManyField(through='Inventory.PurchaseOrderItem', to='Inventory.product'),
        ),
    ]
